# Rust
CARGO_HOME=$HOME/.local/share/cargo
RUSTUP_HOME=$HOME/.local/share/rustup

# JS
NPM_CONFIG_CACHE=$HOME/.cache/npm
#NPM_CONFIG_PREFIX=$HOME/.local/share/npm  # nvm does not like this...

# Java
GRADLE_USER_HOME=$HOME/.cache/gradle
